//! Proof-of-life workflow generated by the ironflow setup.
//!
//! Shows the three things every handler needs: a typed input with a JSON
//! schema (the dashboard renders a form from it), a step, and metadata.

use ironflow_engine::config::ShellConfig;
use ironflow_engine::context::WorkflowContext;
use ironflow_engine::handler::{HandlerFuture, WorkflowHandler, input_schema_for};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::Value;

/// Input payload of the `hello` workflow.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct HelloInput {
    /// Who to greet.
    pub name: String,
}

/// Greets someone through a shell step.
pub struct Hello;

impl WorkflowHandler for Hello {
    fn name(&self) -> &str {
        "hello"
    }

    fn description(&self) -> &str {
        "Greets someone. Proof-of-life workflow generated by the ironflow setup."
    }

    fn source_code(&self) -> Option<&str> {
        Some(include_str!("hello.rs"))
    }

    fn category(&self) -> Option<&str> {
        Some("examples")
    }

    fn input_schema(&self) -> Option<Value> {
        Some(input_schema_for::<HelloInput>())
    }

    fn execute<'a>(&'a self, ctx: &'a mut WorkflowContext) -> HandlerFuture<'a> {
        Box::pin(async move {
            let input: HelloInput = ctx.input().await?;

            // Pass user data through the environment, never by string
            // interpolation into the command line.
            ctx.shell(
                "greet",
                ShellConfig::new("echo \"Hello, $NAME!\"").env("NAME", &input.name),
            )
            .await?;

            Ok(())
        })
    }
}
