[workspace]
resolver = "2"
members = [
    "ironflow-core",
    "ironflow-runtime",
    "ironflow-artifacts",
    "ironflow-store",
    "ironflow-engine",
    "ironflow-api",
    "ironflow-auth",
    "ironflow-worker",
    "examples/ironflow-workflows",
    "examples/server",
    "examples/worker",
    "examples/readme-tests",
    "ironflow-mcp",
    "ironflow-types",
    "ironflow-sdk",
    "ironflow-cli",
]

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
codegen-units = 1
