[package]
name = "ironflow-auth"
version = "2.3.11"
edition = "2024"
rust-version = "1.94"
authors = ["Thomas Tartrau"]
license = "MIT"
description = "Authentication library for ironflow — JWT, password hashing, extractors"
repository = "https://gitlab.com/ThomasTartrau/ironflow"
keywords = ["auth", "jwt", "argon2"]
categories = ["authentication"]

[dependencies]
ironflow-store = { version = "2.14.4", path = "../ironflow-store" }
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
argon2 = { version = "0.5", features = ["std", "rand"] }
serde_json = "1"
axum = { version = "0.8", features = ["json"] }
axum-extra = { version = "0.10", features = ["cookie"] }
cookie = "0.18"
uuid = { version = "1", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
serde_json = "1"
