/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/api-keys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all API keys for the authenticated user. */
		get: operations["list_api_keys"];
		put?: never;
		/**
		 * Create a new API key for the authenticated user.
		 * @description # Errors
		 *
		 *     - 400 if the name is empty or scopes are invalid
		 */
		post: operations["create_api_key"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/api-keys/scopes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Return the list of scopes the current user is allowed to assign to API keys.
		 * @description Admins get all scopes, members only get read-only scopes.
		 */
		get: operations["available_scopes"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/api-keys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete an API key owned by the authenticated user.
		 * @description # Errors
		 *
		 *     - 404 if the key does not exist or belongs to another user
		 */
		delete: operations["delete_api_key"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Return the current user's profile.
		 * @description # Errors
		 *
		 *     - 401 if no valid token is provided
		 *     - 404 if the user no longer exists in the store
		 */
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refresh the access token using a valid refresh token from cookies.
		 * @description # Errors
		 *
		 *     - 401 if the refresh token is missing, invalid, or expired
		 */
		post: operations["refresh"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/sign-in": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticate a user with email and password.
		 * @description Returns access and refresh tokens on success, and sets HttpOnly cookies.
		 *
		 *     # Errors
		 *
		 *     - 401 if email not found or password is wrong
		 */
		post: operations["sign_in"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/sign-out": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sign out the current user by clearing auth cookies. */
		post: operations["sign_out"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health-check": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check handler. Always returns 200 OK. */
		get: operations["health_check"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List runs with optional filtering and pagination.
		 * @description # Query Parameters
		 *
		 *     - `workflow` — Filter by workflow name (optional)
		 *     - `status` — Filter by run status (optional)
		 *     - `page` — Page number, 1-based (default: 1)
		 *     - `per_page` — Items per page (default: 20, max: 100)
		 */
		get: operations["list_runs"];
		put?: never;
		/**
		 * Trigger a workflow by name.
		 * @description Returns 201 Created with the newly enqueued run.
		 *     Returns 400 Bad Request if the workflow is unknown.
		 */
		post: operations["create_run"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a run by ID, including all its steps and dependency edges.
		 * @description Returns 404 if the run does not exist.
		 */
		get: operations["get_run"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs/{id}/approve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Approve a run that is awaiting human approval.
		 * @description Transitions the run from `AwaitingApproval` back to `Running`.
		 *     Returns 400 if the run is not in `AwaitingApproval` state.
		 */
		post: operations["approve_run"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs/{id}/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Cancel a pending or running run.
		 * @description Transitions the run to `Cancelled` status. Returns 400 if the run
		 *     is already in a terminal state.
		 */
		post: operations["cancel_run"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs/{id}/reject": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reject a run that is awaiting human approval.
		 * @description Transitions the run from `AwaitingApproval` to `Failed`.
		 *     Returns 400 if the run is not in `AwaitingApproval` state.
		 */
		post: operations["reject_run"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/runs/{id}/retry": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Retry a failed run.
		 * @description Creates a new `Pending` run with `TriggerKind::Retry` pointing to the
		 *     original. Returns 400 if the run is not in a retryable state.
		 */
		post: operations["retry_run"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/secrets": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List secret metadata. Admin only.
		 * @description Returns key, id, and timestamps. Never returns encrypted or decrypted values.
		 */
		get: operations["list_secrets"];
		put?: never;
		/**
		 * Create or update a secret. Admin only.
		 * @description If the key already exists, the value is replaced. The response
		 *     never includes the secret value.
		 */
		post: operations["create_secret"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/secrets/{key}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Update a secret's value. Admin only.
		 * @description The key is taken from the URL path. The response never includes
		 *     the secret value.
		 *
		 *     # Errors
		 *
		 *     - 403 if the caller is not an admin
		 *     - 404 if the secret key does not exist
		 *     - 400 if the value is invalid
		 */
		put: operations["update_secret"];
		post?: never;
		/**
		 * Delete a secret by key. Admin only.
		 * @description # Errors
		 *
		 *     - 403 if the caller is not an admin
		 *     - 404 if the secret key does not exist
		 */
		delete: operations["delete_secret"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/stats": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get aggregate statistics across runs matching the filter.
		 * @description Accepts the same filtering query parameters as `GET /api/v1/runs`
		 *     (`workflow`, `status`, `has_steps`). `page` and `per_page` are ignored.
		 */
		get: operations["get_stats"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all users with pagination. Admin only.
		 * @description # Errors
		 *
		 *     - 403 if the caller is not an admin
		 */
		get: operations["list_users"];
		put?: never;
		/**
		 * Create a new user account. Admin only.
		 * @description # Errors
		 *
		 *     - 403 if the caller is not an admin
		 *     - 400 if input validation fails
		 *     - 409 if email or username is already taken
		 */
		post: operations["create_user"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete a user account. Admin only.
		 * @description # Errors
		 *
		 *     - 403 if the caller is not an admin
		 *     - 400 if trying to delete self
		 *     - 404 if the user does not exist
		 */
		delete: operations["delete_user"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}/role": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update a user's admin role. Admin only.
		 * @description # Errors
		 *
		 *     - 403 if the caller is not an admin
		 *     - 400 if trying to change own role
		 *     - 404 if the user does not exist
		 */
		patch: operations["update_role"];
		trace?: never;
	};
	"/api/v1/workflows": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List registered workflows, optionally filtered by name and category.
		 * @description # Query Parameters
		 *
		 *     - `name` — Case-insensitive partial match on workflow name (optional)
		 *     - `category` — Case-insensitive partial match on category path, or
		 *       [`UNCATEGORIZED_FILTER`] to filter only uncategorized workflows
		 *       (optional)
		 */
		get: operations["list_workflows"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/workflows/{name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get details about a registered workflow.
		 * @description # Errors
		 *
		 *     - 404 if the workflow is not registered
		 */
		get: operations["get_workflow"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description API key summary (never includes the hash or raw key). */
		ApiKeyResponse: {
			/**
			 * Format: date-time
			 * @description Creation date.
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @description Expiration date.
			 */
			expires_at?: string | null;
			/**
			 * Format: uuid
			 * @description API key ID.
			 */
			id: string;
			/** @description Whether the key is active. */
			is_active: boolean;
			/** @description First characters for identification. */
			key_prefix: string;
			/**
			 * Format: date-time
			 * @description Last used date.
			 */
			last_used_at?: string | null;
			/** @description Key name. */
			name: string;
			/** @description Granted scopes. */
			scopes: components["schemas"]["ApiKeyScope"][];
		};
		/**
		 * @description Permission scope for an API key.
		 *
		 *     Each scope grants access to a specific set of actions.
		 *     A key with no scopes has no permissions.
		 * @enum {string}
		 */
		ApiKeyScope:
			| "workflows_read"
			| "runs_read"
			| "runs_write"
			| "runs_manage"
			| "stats_read"
			| "admin";
		/** @description Request body for creating an API key. */
		CreateApiKeyRequest: {
			/**
			 * Format: date-time
			 * @description Optional expiration date (ISO 8601).
			 */
			expires_at?: string | null;
			/** @description Human-readable name for this key. */
			name: string;
			/** @description Scopes to grant. */
			scopes: components["schemas"]["ApiKeyScope"][];
		};
		/**
		 * @description Response returned when creating an API key.
		 *     The raw key is only shown once.
		 */
		CreateApiKeyResponse: {
			/**
			 * Format: date-time
			 * @description Creation date.
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @description Expiration date.
			 */
			expires_at?: string | null;
			/**
			 * Format: uuid
			 * @description API key ID.
			 */
			id: string;
			/** @description The full raw API key (only returned at creation time). */
			key: string;
			/** @description First characters for identification. */
			key_prefix: string;
			/** @description Key name. */
			name: string;
			/** @description Granted scopes. */
			scopes: components["schemas"]["ApiKeyScope"][];
		};
		/**
		 * @description Request to trigger a workflow.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_api::entities::CreateRunRequest;
		 *     use serde_json::json;
		 *
		 *     let req = CreateRunRequest {
		 *         workflow: "deploy".to_string(),
		 *         payload: Some(json!({"env": "prod"})),
		 *     };
		 *     assert_eq!(req.workflow, "deploy");
		 *     ```
		 */
		CreateRunRequest: {
			/** @description Optional input payload for the workflow. */
			payload?: {
				[key: string]: unknown;
			} | null;
			/** @description The workflow name to trigger. */
			workflow: string;
		};
		/** @description Request body for creating a user (admin only). */
		CreateUserRequest: {
			/** @description Email address. */
			email: string;
			/** @description Whether the new user should be an admin. */
			is_admin: boolean;
			/** @description Plaintext password (min 8 characters). */
			password: string;
			/** @description Display username. */
			username: string;
		};
		/**
		 * @description A domain event emitted by the ironflow system.
		 *
		 *     Covers the full lifecycle: runs, steps, approvals, and authentication.
		 *     Subscribers receive these via [`EventPublisher`](super::EventPublisher)
		 *     and pattern-match on the variants they care about.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_engine::notify::Event;
		 *     use ironflow_store::models::RunStatus;
		 *     use uuid::Uuid;
		 *
		 *     let event = Event::RunStatusChanged {
		 *         run_id: Uuid::now_v7(),
		 *         workflow_name: "deploy".to_string(),
		 *         from: RunStatus::Running,
		 *         to: RunStatus::Completed,
		 *         error: None,
		 *         cost_usd: rust_decimal::Decimal::ZERO,
		 *         duration_ms: 5000,
		 *         at: chrono::Utc::now(),
		 *     };
		 *     ```
		 */
		Event:
			| {
					/**
					 * Format: date-time
					 * @description When the run was created.
					 */
					at: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/** @enum {string} */
					type: "run_created";
					/** @description Workflow name. */
					workflow_name: string;
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the transition occurred.
					 */
					at: string;
					/**
					 * Format: double
					 * @description Aggregated cost in USD at the time of transition.
					 */
					cost_usd: number;
					/**
					 * Format: int64
					 * @description Aggregated duration in milliseconds at the time of transition.
					 */
					duration_ms: number;
					/** @description Error message (when transitioning to Failed). */
					error?: string | null;
					/** @description Previous status. */
					from: components["schemas"]["RunStatus"];
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/** @description New status. */
					to: components["schemas"]["RunStatus"];
					/** @enum {string} */
					type: "run_status_changed";
					/** @description Workflow name. */
					workflow_name: string;
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the failure occurred.
					 */
					at: string;
					/**
					 * Format: double
					 * @description Aggregated cost in USD at the time of failure.
					 */
					cost_usd: number;
					/**
					 * Format: int64
					 * @description Aggregated duration in milliseconds at the time of failure.
					 */
					duration_ms: number;
					/** @description Error message. */
					error?: string | null;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/** @enum {string} */
					type: "run_failed";
					/** @description Workflow name. */
					workflow_name: string;
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the step completed.
					 */
					at: string;
					/**
					 * Format: double
					 * @description Step cost in USD.
					 */
					cost_usd: number;
					/**
					 * Format: int64
					 * @description Step duration in milliseconds.
					 */
					duration_ms: number;
					/** @description Step operation kind. */
					kind: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/**
					 * Format: uuid
					 * @description Step identifier.
					 */
					step_id: string;
					/** @description Human-readable step name. */
					step_name: string;
					/** @enum {string} */
					type: "step_completed";
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the step failed.
					 */
					at: string;
					/** @description Error message. */
					error: string;
					/** @description Step operation kind. */
					kind: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/**
					 * Format: uuid
					 * @description Step identifier.
					 */
					step_id: string;
					/** @description Human-readable step name. */
					step_name: string;
					/** @enum {string} */
					type: "step_failed";
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the approval was requested.
					 */
					at: string;
					/** @description Message displayed to reviewers. */
					message: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/**
					 * Format: uuid
					 * @description Approval step identifier.
					 */
					step_id: string;
					/** @enum {string} */
					type: "approval_requested";
			  }
			| {
					/** @description User who approved (ID or username). */
					approved_by: string;
					/**
					 * Format: date-time
					 * @description When the approval was granted.
					 */
					at: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/** @enum {string} */
					type: "approval_granted";
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the rejection occurred.
					 */
					at: string;
					/** @description User who rejected (ID or username). */
					rejected_by: string;
					/**
					 * Format: uuid
					 * @description Run identifier.
					 */
					run_id: string;
					/** @enum {string} */
					type: "approval_rejected";
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the sign-in occurred.
					 */
					at: string;
					/** @enum {string} */
					type: "user_signed_in";
					/**
					 * Format: uuid
					 * @description User identifier.
					 */
					user_id: string;
					/** @description Username. */
					username: string;
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the sign-up occurred.
					 */
					at: string;
					/** @enum {string} */
					type: "user_signed_up";
					/**
					 * Format: uuid
					 * @description User identifier.
					 */
					user_id: string;
					/** @description Username. */
					username: string;
			  }
			| {
					/**
					 * Format: date-time
					 * @description When the sign-out occurred.
					 */
					at: string;
					/** @enum {string} */
					type: "user_signed_out";
					/**
					 * Format: uuid
					 * @description User identifier.
					 */
					user_id: string;
			  };
		/**
		 * @description Strongly-typed event kind matching [`Event`] variants.
		 *
		 *     Serializes to/from the same `snake_case` strings as
		 *     [`Event::event_type()`].
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_api::routes::events::EventKind;
		 *
		 *     let kind: EventKind = "run_status_changed".parse().unwrap();
		 *     assert_eq!(kind, EventKind::RunStatusChanged);
		 *     assert_eq!(kind.as_str(), "run_status_changed");
		 *     ```
		 * @enum {string}
		 */
		EventKind:
			| "run_created"
			| "run_status_changed"
			| "run_failed"
			| "step_completed"
			| "step_failed"
			| "approval_requested"
			| "approval_granted"
			| "approval_rejected"
			| "user_signed_in"
			| "user_signed_up"
			| "user_signed_out";
		/** @description Query parameters for listing runs. */
		ListRunsQuery: {
			/**
			 * @description When `true`, only return runs with at least one step.
			 *     When `false`, only return runs with no steps.
			 */
			has_steps?: boolean | null;
			/**
			 * Format: int32
			 * @description Page number (1-based).
			 */
			page?: number | null;
			/**
			 * Format: int32
			 * @description Items per page.
			 */
			per_page?: number | null;
			status?: null | components["schemas"]["RunStatus"];
			/** @description Filter by workflow name. */
			workflow?: string | null;
		};
		/** @description Query parameters for listing users. */
		ListUsersQuery: {
			/**
			 * Format: int32
			 * @description Page number (1-based, defaults to 1).
			 */
			page?: number | null;
			/**
			 * Format: int32
			 * @description Items per page (defaults to 20, max 100).
			 */
			per_page?: number | null;
		};
		/** @description Query parameters for listing workflows. */
		ListWorkflowsQuery: {
			/**
			 * @description Optional case-insensitive partial match on the category path
			 *     (e.g. `etl` matches `Data/ETL` and `data/etl/nightly`).
			 *
			 *     Pass `__uncategorized__` to list only workflows without any
			 *     category.
			 */
			category?: string | null;
			/** @description Optional case-insensitive partial match on workflow name. */
			name?: string | null;
		};
		/** @description Current user profile response. */
		MeResponse: {
			/** @description Email address. */
			email: string;
			/** @description Admin flag. */
			is_admin: boolean;
			/**
			 * Format: uuid
			 * @description User ID.
			 */
			user_id: string;
			/** @description Display username. */
			username: string;
		};
		/** @description Run detail response — includes steps. */
		RunDetailResponse: {
			/** @description The run. */
			run: components["schemas"]["RunResponse"];
			/** @description Associated steps, ordered by position. */
			steps: components["schemas"]["StepResponse"][];
		};
		/**
		 * @description Run response DTO — public API representation of a run.
		 *
		 *     Maps from the internal [`Run`] model, exposing only necessary fields.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_store::models::{Run, RunStatus, TriggerKind};
		 *     use ironflow_api::entities::RunResponse;
		 *     ```
		 */
		RunResponse: {
			/**
			 * Format: date-time
			 * @description When execution completed.
			 */
			completed_at?: string | null;
			/**
			 * Format: double
			 * @description Aggregated cost in USD.
			 */
			cost_usd: number;
			/**
			 * Format: date-time
			 * @description When created.
			 */
			created_at: string;
			/**
			 * Format: int64
			 * @description Total duration in milliseconds.
			 */
			duration_ms: number;
			/** @description Optional error message. */
			error?: string | null;
			/** @description Version of the handler that created this run. */
			handler_version?: string | null;
			/**
			 * Format: uuid
			 * @description Unique run identifier.
			 */
			id: string;
			/**
			 * Format: int32
			 * @description Maximum allowed retries.
			 */
			max_retries: number;
			/**
			 * Format: int32
			 * @description Number of times retried.
			 */
			retry_count: number;
			/**
			 * Format: date-time
			 * @description When execution started.
			 */
			started_at?: string | null;
			/** @description Current status. */
			status: components["schemas"]["RunStatus"];
			/** @description How the run was triggered. */
			trigger: components["schemas"]["TriggerKind"];
			/**
			 * Format: date-time
			 * @description When last updated.
			 */
			updated_at: string;
			/** @description Workflow name. */
			workflow_name: string;
		};
		/**
		 * @description Status of a workflow run, forming a finite state machine.
		 *
		 *     Valid transitions:
		 *     - `Pending` → `Running`, `Cancelled`
		 *     - `Running` → `Completed`, `Failed`, `Retrying`, `Cancelled`, `AwaitingApproval`
		 *     - `Retrying` → `Running`, `Failed`, `Cancelled`
		 *     - `AwaitingApproval` → `Running`, `Failed`, `Cancelled`
		 *
		 *     Terminal states: `Completed`, `Failed`, `Cancelled`.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_store::entities::RunStatus;
		 *
		 *     assert!(RunStatus::Pending.can_transition_to(&RunStatus::Running));
		 *     assert!(!RunStatus::Pending.can_transition_to(&RunStatus::Completed));
		 *     assert!(!RunStatus::Completed.can_transition_to(&RunStatus::Running));
		 *     assert!(RunStatus::Running.can_transition_to(&RunStatus::AwaitingApproval));
		 *     assert!(RunStatus::AwaitingApproval.can_transition_to(&RunStatus::Running));
		 *     ```
		 * @enum {string}
		 */
		RunStatus:
			| "pending"
			| "running"
			| "completed"
			| "failed"
			| "retrying"
			| "cancelled"
			| "awaiting_approval";
		/** @description A scope entry with its machine name and human-readable label. */
		ScopeEntry: {
			/** @description Short description. */
			description: string;
			/** @description Human-readable label (e.g. "Runs Read"). */
			label: string;
			/** @description Machine-readable scope value (e.g. "runs_read"). */
			value: string;
		};
		/** @description Response DTO for a secret (never exposes the value). */
		SecretResponse: {
			/**
			 * Format: date-time
			 * @description Creation timestamp.
			 */
			created_at: string;
			/**
			 * Format: uuid
			 * @description Secret ID.
			 */
			id: string;
			/** @description Secret key. */
			key: string;
			/**
			 * Format: date-time
			 * @description Last update timestamp.
			 */
			updated_at: string;
		};
		/** @description Request body for creating or updating a secret. */
		SetSecretRequest: {
			/** @description Secret key (namespaced, e.g. `workflows/inbox/gmail_token`). */
			key: string;
			/** @description Secret value (plaintext, will be encrypted at rest). */
			value: string;
		};
		/** @description Sign-in request body. */
		SignInRequest: {
			/** @description Email address. */
			email: string;
			/** @description Plaintext password. */
			password: string;
		};
		/**
		 * @description Aggregate statistics response.
		 *
		 *     Computed from all runs in the store.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_api::entities::StatsResponse;
		 *     ```
		 */
		StatsResponse: {
			/**
			 * Format: int64
			 * @description Number of pending or running runs.
			 */
			active_runs: number;
			/**
			 * Format: int64
			 * @description Number of cancelled runs.
			 */
			cancelled_runs: number;
			/**
			 * Format: int64
			 * @description Number of completed runs.
			 */
			completed_runs: number;
			/**
			 * Format: int64
			 * @description Number of failed runs.
			 */
			failed_runs: number;
			/**
			 * Format: double
			 * @description Success rate: completed / (completed + failed), as a percentage.
			 */
			success_rate_percent: number;
			/**
			 * Format: double
			 * @description Aggregated cost across all runs in USD.
			 */
			total_cost_usd: number;
			/**
			 * Format: int64
			 * @description Aggregated duration across all runs in milliseconds.
			 */
			total_duration_ms: number;
			/**
			 * Format: int64
			 * @description Total number of runs.
			 */
			total_runs: number;
		};
		/**
		 * @description Step response DTO — public API representation of a step.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_store::models::Step;
		 *     use ironflow_api::entities::StepResponse;
		 *     ```
		 */
		StepResponse: {
			/**
			 * Format: date-time
			 * @description When execution completed.
			 */
			completed_at?: string | null;
			/**
			 * Format: double
			 * @description Cost in USD.
			 */
			cost_usd: number;
			/**
			 * Format: date-time
			 * @description When created.
			 */
			created_at: string;
			/**
			 * @description Verbose conversation trace for agent steps (thinking blocks, tool
			 *     calls, tool results, per-turn usage). `None` when verbose mode was
			 *     off or the step is not an agent step.
			 */
			debug_messages?: unknown;
			/** @description IDs of steps this step depends on (direct dependencies). */
			dependencies: string[];
			/**
			 * Format: int64
			 * @description Execution duration in milliseconds.
			 */
			duration_ms: number;
			/** @description Optional error message. */
			error?: string | null;
			/**
			 * Format: uuid
			 * @description Unique step identifier.
			 */
			id: string;
			/** @description Input configuration. */
			input?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Format: int64
			 * @description Input token count (agent steps).
			 */
			input_tokens?: number | null;
			/** @description Step operation type. */
			kind: string;
			/** @description Step name. */
			name: string;
			/** @description Step output. */
			output?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Format: int64
			 * @description Output token count (agent steps).
			 */
			output_tokens?: number | null;
			/**
			 * Format: int32
			 * @description Execution order (0-based).
			 */
			position: number;
			/**
			 * Format: uuid
			 * @description Parent run ID.
			 */
			run_id: string;
			/**
			 * Format: date-time
			 * @description When execution started.
			 */
			started_at?: string | null;
			/** @description Current status. */
			status: components["schemas"]["StepStatus"];
			/**
			 * Format: date-time
			 * @description When updated.
			 */
			updated_at: string;
		};
		/**
		 * @description Status of an individual step within a run.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_store::entities::StepStatus;
		 *
		 *     assert!(!StepStatus::Pending.is_terminal());
		 *     assert!(StepStatus::Completed.is_terminal());
		 *     ```
		 * @enum {string}
		 */
		StepStatus:
			| "pending"
			| "running"
			| "completed"
			| "failed"
			| "skipped"
			| "awaiting_approval"
			| "rejected";
		/** @description Sub-workflow detail included in the workflow response. */
		SubWorkflowDetail: {
			/** @description Human-readable description. */
			description: string;
			/** @description Sub-workflow name. */
			name: string;
			/** @description Optional Rust source code of the handler. */
			source_code?: string | null;
		};
		/**
		 * @description How a run was triggered.
		 *
		 *     # Examples
		 *
		 *     ```
		 *     use ironflow_store::entities::TriggerKind;
		 *
		 *     let trigger = TriggerKind::Manual;
		 *     let json = serde_json::to_string(&trigger).unwrap();
		 *     assert!(json.contains("manual"));
		 *     ```
		 */
		TriggerKind:
			| {
					/** @enum {string} */
					kind: "manual";
			  }
			| {
					/** @enum {string} */
					kind: "webhook";
					/** @description The webhook path that received the request. */
					path: string;
			  }
			| {
					/** @enum {string} */
					kind: "cron";
					/** @description The cron expression that fired. */
					schedule: string;
			  }
			| {
					/** @enum {string} */
					kind: "api";
			  }
			| {
					/** @enum {string} */
					kind: "retry";
					/**
					 * Format: uuid
					 * @description The original run that failed.
					 */
					parent_run_id: string;
			  }
			| {
					/** @enum {string} */
					kind: "workflow";
			  };
		/** @description Request body for updating a user's role (admin only). */
		UpdateRoleRequest: {
			/** @description New admin status. */
			is_admin: boolean;
		};
		/** @description Request body for updating a secret value. */
		UpdateSecretRequest: {
			/** @description New secret value (plaintext, will be encrypted at rest). */
			value: string;
		};
		/** @description Response DTO for a user (never exposes password hash). */
		UserResponse: {
			/**
			 * Format: date-time
			 * @description Creation timestamp.
			 */
			created_at: string;
			/** @description Email address. */
			email: string;
			/**
			 * Format: uuid
			 * @description User ID.
			 */
			id: string;
			/** @description Whether the user is an admin. */
			is_admin: boolean;
			/**
			 * Format: date-time
			 * @description Last update timestamp.
			 */
			updated_at: string;
			/** @description Display username. */
			username: string;
		};
		/** @description Workflow detail response. */
		WorkflowDetailResponse: {
			/** @description Optional `/`-separated category path used to group workflows. */
			category?: string | null;
			/** @description Human-readable description. */
			description: string;
			/** @description Workflow name. */
			name: string;
			/** @description Optional Rust source code of the handler. */
			source_code?: string | null;
			/** @description Sub-workflows invoked by this handler (recursive, depth-limited). */
			sub_workflows: components["schemas"]["SubWorkflowDetail"][];
			/** @description Current handler version. */
			version: string;
		};
		/** @description Summary entry returned by `GET /api/v1/workflows`. */
		WorkflowSummary: {
			/** @description Optional `/`-separated category path. */
			category?: string | null;
			/** @description Workflow name (unique identifier). */
			name: string;
			/** @description Current handler version. */
			version: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_api_keys: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of API keys */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyResponse"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_api_key: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description API key configuration */
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateApiKeyRequest"];
			};
		};
		responses: {
			/** @description API key created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreateApiKeyResponse"];
				};
			};
			/** @description Invalid input */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden (member trying to assign forbidden scopes) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	available_scopes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of available scopes */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ScopeEntry"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_api_key: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description API key ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description API key deleted successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description API key not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current user profile */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeResponse"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	refresh: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Access token refreshed successfully, new cookies set */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid or expired refresh token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	sign_in: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Sign in credentials */
		requestBody: {
			content: {
				"application/json": components["schemas"]["SignInRequest"];
			};
		};
		responses: {
			/** @description User authenticated successfully, cookies set */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid email or password */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	sign_out: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User signed out successfully, cookies cleared */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	health_check: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service is healthy */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_runs: {
		parameters: {
			query?: {
				/** @description Filter by workflow name. */
				workflow?: string | null;
				/** @description Filter by run status. */
				status?: null | components["schemas"]["RunStatus"];
				/**
				 * @description When `true`, only return runs with at least one step.
				 *     When `false`, only return runs with no steps.
				 */
				has_steps?: boolean | null;
				/** @description Page number (1-based). */
				page?: number | null;
				/** @description Items per page. */
				per_page?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of runs with pagination */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_run: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Workflow to trigger */
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateRunRequest"];
			};
		};
		responses: {
			/** @description Run created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunResponse"];
				};
			};
			/** @description Unknown workflow */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_run: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Run ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Run details with steps */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunDetailResponse"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	approve_run: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Run ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Run approved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunResponse"];
				};
			};
			/** @description Run not awaiting approval */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	cancel_run: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Run ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Run cancelled successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunResponse"];
				};
			};
			/** @description Run cannot be cancelled */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	reject_run: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Run ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Run rejected successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunResponse"];
				};
			};
			/** @description Run not awaiting approval */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	retry_run: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Run ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Run retry created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunResponse"];
				};
			};
			/** @description Run cannot be retried */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_secrets: {
		parameters: {
			query?: {
				/** @description Filter by key prefix (e.g. `workflows/inbox/`). */
				prefix?: string | null;
				/** @description Page number (1-based, default 1). */
				page?: number | null;
				/** @description Items per page (default 50, max 100). */
				per_page?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Secrets listed */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SecretResponse"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_secret: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Secret key and value */
		requestBody: {
			content: {
				"application/json": components["schemas"]["SetSecretRequest"];
			};
		};
		responses: {
			/** @description Secret created or updated */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SecretResponse"];
				};
			};
			/** @description Invalid input */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_secret: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Secret key */
				key: string;
			};
			cookie?: never;
		};
		/** @description New secret value */
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateSecretRequest"];
			};
		};
		responses: {
			/** @description Secret updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SecretResponse"];
				};
			};
			/** @description Invalid input */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Secret not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_secret: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Secret key */
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Secret deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Secret not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_stats: {
		parameters: {
			query?: {
				/** @description Filter by workflow name. */
				workflow?: string | null;
				/** @description Filter by run status. */
				status?: null | components["schemas"]["RunStatus"];
				/**
				 * @description When `true`, only return runs with at least one step.
				 *     When `false`, only return runs with no steps.
				 */
				has_steps?: boolean | null;
				/** @description Page number (1-based). */
				page?: number | null;
				/** @description Items per page. */
				per_page?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Aggregate statistics */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StatsResponse"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_users: {
		parameters: {
			query?: {
				/** @description Page number (1-based, defaults to 1). */
				page?: number | null;
				/** @description Items per page (defaults to 20, max 100). */
				per_page?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Paginated list of users */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserResponse"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden (not an admin) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description User account details */
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateUserRequest"];
			};
		};
		responses: {
			/** @description User created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserResponse"];
				};
			};
			/** @description Invalid input */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden (not an admin) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Email or username already taken */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User deleted successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Cannot delete self */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden (not an admin) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_role: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User ID */
				id: string;
			};
			cookie?: never;
		};
		/** @description New role assignment */
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateRoleRequest"];
			};
		};
		responses: {
			/** @description User role updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserResponse"];
				};
			};
			/** @description Cannot change own role */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden (not an admin) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_workflows: {
		parameters: {
			query?: {
				/** @description Optional case-insensitive partial match on workflow name. */
				name?: string | null;
				/**
				 * @description Optional case-insensitive partial match on the category path
				 *     (e.g. `etl` matches `Data/ETL` and `data/etl/nightly`).
				 *
				 *     Pass `__uncategorized__` to list only workflows without any
				 *     category.
				 */
				category?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of workflow summaries */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkflowSummary"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_workflow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Workflow name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Workflow details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkflowDetailResponse"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Workflow not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
